"""empty message

Revision ID: 08cc7bae3e63
Revises: dacbdb8c9751
Create Date: 2025-11-20 00:40:38.399685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cc7bae3e63'
down_revision = 'dacbdb8c9751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sender_username', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('sender_username')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
